Repository depromeet/kok-server, pull requests merged in 2025-03, with the labels that each got.

#40 🚀[Deploy/dev cd] dev cd configuration
  .github/workflows/kok-dev-CD.yml
  .gitignore
  infra/docker-compose-blue.yml
  infra/docker-compose-dev.yml
  infra/docker-compose-green.yml
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/LocationRequest.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/rest/LocationController.java
Labels: deploy, 🥇 Urgency 1

#38 ✨ [Feature/testcontainers] implement testcontainers
  kok-api/build.gradle
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
  kok-api/src/test/java/com/kok/kokapi/common/template/ContainerBaseTest.java
  kok-api/src/test/java/com/kok/kokapi/common/template/RepositoryTest.java
  kok-api/src/test/java/com/kok/kokapi/common/template/ServiceTest.java
  kok-api/src/test/java/com/kok/kokapi/common/util/MySQLDatabaseCleaner.java
  kok-api/src/test/java/com/kok/kokapi/common/util/MySQLDatabaseCleanerExtension.java
  kok-api/src/test/java/com/kok/kokapi/config/DataJpaTestConfig.java
  kok-api/src/test/java/com/kok/kokapi/config/ServiceTestConfig.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomCreationServiceTest.java
  kok-api/src/test/java/com/kok/kokapi/station/adapter/out/persistence/StationRepositoryTest.java
  kok-api/src/test/java/com/kok/kokapi/station/application/service/StationServiceTest.java
  kok-api/src/test/resources/application-test.yml
Labels: ✨ Feature

#41 :bug: fix: update cors config
  kok-api/src/main/java/com/kok/kokapi/config/web/WebMvcConfig.java
Labels: bug

#42 :bug: fix: enable flyway.baseline-on-migrate to initialize schema history
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
Labels: bug

#43 🚀[Deploy/dev cd] change swagger path
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/rest/LocationController.java
  kok-api/src/main/resources/application-dev.yml
Labels: bug, deploy, 🥇 Urgency 1

#44 🐛 [FIX/redis_connection] change dev redis to instance local
  .github/workflows/kok-dev-CD.yml
  infra/docker-compose-dev.yml
  kok-api/src/main/resources/application-dev.yml
Labels: bug, 🥇 Urgency 1

#45 🐛 [FIX/redis_connection] change dev redis to instance local with .env file
  infra/docker-compose-dev.yml
  kok-api/src/main/resources/application-dev.yml
Labels: bug, deploy, 🥇 Urgency 1

#46 :recycle: [Refactor/BaseController] Replace BaseController with annotion
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/rest/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/common/adapter/in/web/BaseController.java
  kok-api/src/main/java/com/kok/kokapi/config/annotion/V1Controller.java
  kok-api/src/main/java/com/kok/kokapi/monitoring/adapter/in/web/HealthCheckController.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
Labels: refactor

#49 :sparkles: [Feature/Room] implement finding Room for Client Sharing link
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomDetailResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomQueryServiceTest.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
Labels: ✨ Feature

#51 ✨[Feature/Convex-Hull]: add ConvexHull logic for return locations
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/request/LocationRequest.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/response/CentroidResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/response/ConvexHullLocationResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/response/LocationResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/web/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/mapper/LocationMapper.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationRepository.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationQueryService.java
  kok-core/src/main/java/com/kok/kokcore/location/application/port/out/ReadLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/ReadLocationUsecase.java
Labels: ✨ Feature, 🥉Urgency 3

#47 ✨[Feature/route] implement public transportation time and transit count
  kok-api/src/main/java/com/kok/kokapi/config/redis/out/RedisPublicTransportationCacheConfig.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/in/dto/RouteRequest.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/in/dto/RouteResponse.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/in/web/PublicTransfortationController.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/out/external/PublicTransportationClient.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/out/external/TmapClientProperties.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/out/external/dto/TmapPublicTransportationResponse.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/application/service/TmapPublicTransportationService.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationRepository.java
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
  kok-core/src/main/java/com/kok/kokcore/public_transfortation/usecase/RetrievePublicTransportationUsecase.java
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/RetrieveStationsPort.java
Labels: ✨ Feature, 🥈Urgency 2

#54 🐛 [Fix/station-normalization] normalize station table
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/external/StationClient.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/external/StationErrorHandler.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/external/dto/StationResponse.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/external/dto/StationResponses.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/RoutePersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationRepository.java
  kok-api/src/main/java/com/kok/kokapi/station/application/config/StationsConfig.java
  kok-api/src/main/java/com/kok/kokapi/station/application/service/StationService.java
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/db/V1__init_station.sql
  kok-api/src/test/java/com/kok/kokapi/common/template/ContainerBaseTest.java
  kok-api/src/test/java/com/kok/kokapi/station/adapter/out/external/FakeStationClient.java
  kok-api/src/test/java/com/kok/kokapi/station/adapter/out/persistence/StationPersistenceAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/station/adapter/out/persistence/StationRepositoryTest.java
  kok-api/src/test/java/com/kok/kokapi/station/application/service/StationServiceTest.java
  kok-api/src/test/resources/application-test.yml
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/LoadStationsPort.java
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/SaveRoutePort.java
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/SaveStationsPort.java
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/dto/StationRouteDto.java
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/dto/StationRouteDtos.java
  kok-core/src/main/java/com/kok/kokcore/station/domain/entity/Route.java
  kok-core/src/main/java/com/kok/kokcore/station/domain/entity/Station.java
  kok-core/src/test/java/com/kok/kokcore/station/application/port/out/dto/StationRouteDtosTest.java
Labels: ✨ Feature, 🥇 Urgency 1

#64 🐛 [Fix/flyway] fix flyway and activate
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
  kok-api/src/main/resources/db/data/priority.sql
  kok-api/src/main/resources/db/migration/V1__init.sql
  kok-api/src/test/resources/application-test.yml
Labels: bug, 🥉Urgency 3

#61 :bug: [Fix/test] fix test for missing configuration
  kok-api/src/test/java/com/kok/kokapi/KokApiApplicationTests.java
  kok-api/src/test/java/com/kok/kokapi/common/template/ServiceTest.java
  kok-api/src/test/resources/application-test.yml
Labels: bug, 🥈Urgency 2

#69 ♻️ [Fix/appointment-room] update room response and change new profile images
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/request/CreateRoomRequest.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/JoinRoomResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/MemberResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomCreateResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomMembersResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomProfileController.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RoomParticipantQueryAdapter.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RandomProfileService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomParticipantService.java
  kok-core/src/main/java/com/kok/kokcore/room/application/port/out/LoadRoomParticipantsPort.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Member.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/GetMemberProfileUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1

#65 :sparkles: [Feature/subway-recommend] add station recommend
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/request/LocationRequest.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/response/CentroidResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/response/LocationResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/web/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/mapper/LocationMapper.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationRepository.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/CentroidQueryService.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationCommandService.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationQueryService.java
  kok-api/src/main/java/com/kok/kokapi/config/redis/out/RedisCacheConfig.java
  kok-api/src/main/java/com/kok/kokapi/config/redis/out/RedisPublicTransportationCacheConfig.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/in/dto/RouteRequest.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/in/web/PublicTransportationController.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/out/external/PublicTransportationClient.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/adapter/out/external/PublicTransportationComplexClient.java
  kok-api/src/main/java/com/kok/kokapi/public_transportation/application/service/TmapPublicTransportationService.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/in/dto/response/RecommendedStationResponse.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/in/web/StationController.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/RoutePersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/RouteRepository.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationRepository.java
  kok-api/src/main/java/com/kok/kokapi/station/application/service/RouteService.java
  kok-api/src/main/java/com/kok/kokapi/station/application/service/StationService.java
  kok-api/src/main/resources/db/migration/V1__init.sql
  kok-core/src/main/java/com/kok/kokcore/location/application/port/out/ReadCentroidPort.java
  kok-core/src/main/java/com/kok/kokcore/location/application/port/out/ReadLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/location/application/port/out/SaveLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/location/domain/Location.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/CreateLocationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/CreateLocationUsecase.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/LoadCentroidUseCase.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/ReadLocationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/ReadLocationUsecase.java
  kok-core/src/main/java/com/kok/kokcore/public_transfortation/usecase/RetrievePublicTransportationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/public_transfortation/usecase/RetrievePublicTransportationUsecase.java
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/RetrieveRoutePort.java
  kok-core/src/main/java/com/kok/kokcore/station/application/port/out/RetrieveStationsPort.java
  kok-core/src/main/java/com/kok/kokcore/station/application/usecase/RecommendStationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/station/application/usecase/RetrieveRouteUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1

#76 ✨ [Feature/RoomParticipant] add boolean field if room is full for getting profile list
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomDetailResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomMembersResponses.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/test/java/com/kok/kokapi/room/adapter/in/web/RoomIntegrationTest.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
Labels: ✨ Feature, 🥇 Urgency 1

#81 :sparkles: [feature/custom-candidate]: add custom voting candidate function
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/request/LocationRequest.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/response/LocationResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/web/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/mapper/LocationMapper.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationCommandService.java
  kok-api/src/main/java/com/kok/kokapi/config/redis/RedisCacheConfig.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/in/web/StationController.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationRepository.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/UserRecommendStationCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/UserRecommendStationQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/application/service/StationFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/station/application/service/StationService.java
  kok-api/src/main/resources/db/migration/V2__add_location_name.sql
  kok-api/src/test/java/com/kok/kokapi/room/adapter/in/web/RoomIntegrationTest.java
  kok-core/src/main/java/com/kok/kokcore/location/domain/Location.java
  kok-core/src/main/java/com/kok/kokcore/location/port/out/SaveLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/CreateLocationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/station/port/out/ReadUserRecommendStationsPort.java
  kok-core/src/main/java/com/kok/kokcore/station/port/out/RetrieveStationsPort.java
  kok-core/src/main/java/com/kok/kokcore/station/port/out/SaveUserRecommendStationsPort.java
  kok-core/src/main/java/com/kok/kokcore/station/usecase/SystemRecommendUseCase.java
  kok-core/src/main/java/com/kok/kokcore/station/usecase/UserRecommendUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1

#78 ✨ [Feature/vote] implement getting candidates API
  kok-api/src/main/java/com/kok/kokapi/common/exception/GlobalExceptionHandler.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/RoutePersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/RouteRepository.java
  kok-api/src/main/java/com/kok/kokapi/station/application/service/StationService.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/CandidateResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/CommentResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/CandidateService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-api/src/test/java/com/kok/kokapi/common/util/MySQLDatabaseCleaner.java
  kok-api/src/test/java/com/kok/kokapi/station/application/service/StationServiceTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateCommandRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateQueryRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapterTest.java
  kok-core/src/main/java/com/kok/kokcore/station/domain/entity/Station.java
  kok-core/src/main/java/com/kok/kokcore/station/port/out/LoadRecommendedStationsPort.java
  kok-core/src/main/java/com/kok/kokcore/station/usecase/GetStationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/vote/application/port/out/LoadCandidatePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/application/port/out/SaveCandidatePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/application/port/out/SaveVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/Candidate.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/Vote.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/vo/VoteStatus.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/CreateVoteUseCase.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetCandidateUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1

#79 ✨ [Feature/vote] implement save vote API
  kok-api/build.gradle
  kok-api/src/main/java/com/kok/kokapi/common/util/RedisExecutor.java
  kok-api/src/main/java/com/kok/kokapi/config/redis/RedisConfig.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/StationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/request/VoteRequest.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/RouteResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/CandidateService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
  kok-api/src/test/java/com/kok/kokapi/station/application/service/StationServiceTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/application/service/VoteServiceTest.java
  kok-core/src/main/java/com/kok/kokcore/vote/application/port/out/SaveVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/Vote.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/vo/VoteStatus.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/DeleteVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/LoadCandidatePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/LoadVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/SaveCandidatePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/SaveVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetCandidateUseCase.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/SaveVoteUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1

#80 ✨ [Feature/vote] implement getting members vote status API
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RoomParticipantQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RoomQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/RouteRepository.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/UserRecommendStationCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/UserRecommendStationQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/MemberVoteStatusResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
  kok-api/src/test/java/com/kok/kokapi/vote/application/service/VoteServiceTest.java
  kok-core/src/main/java/com/kok/kokcore/room/port/out/LoadRoomParticipantPort.java
  kok-core/src/main/java/com/kok/kokcore/room/port/out/LoadRoomPort.java
  kok-core/src/main/java/com/kok/kokcore/station/usecase/DeleteRecommendStationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/station/usecase/GetRecommendStationUseCase.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/CreateVoteUseCase.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetVoteUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1

#83 :sparkles: [Feature/location] add member profile image field to LocationResponse
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/response/LocationResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/web/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/mapper/LocationMapper.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/GetRoomUseCase.java
Labels: ✨ Feature

#86 ✨ [Feature/room] add isVoteMode field on RoomDetailResponse
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomDetailResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomFacadeService.java
  kok-api/src/test/java/com/kok/kokapi/room/adapter/in/web/RoomIntegrationTest.java
Labels: ✨ Feature, 🥇 Urgency 1

#87 ✨ [Feature/vote] implement getting vote deadline API
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/web/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RoomSaveRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomCommandService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomCreationService.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VoteDeadlineResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/test/java/com/kok/kokapi/room/adapter/out/persistence/RoomSaveRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomCommandServiceTest.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
  kok-core/src/main/java/com/kok/kokcore/room/port/out/UpdateRoomPort.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/UpdateRoomUseCase.java
  kok-core/src/test/java/com/kok/kokcore/room/domain/RoomTest.java
Labels: ✨ Feature

#88 :sparkles: [Feature/places] implements google search place API
  kok-api/src/main/java/com/kok/kokapi/place/adapter/in/dto/request/PlacesRequest.java
  kok-api/src/main/java/com/kok/kokapi/place/adapter/in/dto/response/PlaceResponse.java
  kok-api/src/main/java/com/kok/kokapi/place/adapter/in/dto/response/PlacesResponse.java
  kok-api/src/main/java/com/kok/kokapi/place/adapter/in/web/PlacesController.java
  kok-api/src/main/java/com/kok/kokapi/place/adapter/out/external/GooglePlaceApiAdapter.java
  kok-api/src/main/java/com/kok/kokapi/place/application/service/PlacesService.java
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
  kok-core/src/main/java/com/kok/kokcore/places/domain/model/Place.java
  kok-core/src/main/java/com/kok/kokcore/places/domain/model/PlacesResult.java
  kok-core/src/main/java/com/kok/kokcore/places/domain/model/vo/PlaceType.java
  kok-core/src/main/java/com/kok/kokcore/places/port/in/PlaceInput.java
  kok-core/src/main/java/com/kok/kokcore/places/port/out/LoadPlacesPort.java
  kok-core/src/main/java/com/kok/kokcore/places/usecase/SearchPlaceUseCase.java
Labels: ✨ Feature, 🥈Urgency 2

#92 🐛 [Fix/profile-response] add address field to RoomParticipantResponse
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomMembersResponses.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomParticipantResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomParticipantsResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomProfileController.java
Labels: 🥇 Urgency 1, fix

#97 ✨ [Feature/room] change isVoteMode to roomStatus on API
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/web/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomDetailResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomStatusResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomCommandService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/test/java/com/kok/kokapi/room/adapter/in/web/RoomIntegrationTest.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomQueryServiceTest.java
  kok-api/src/test/resources/application-test.yml
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/vo/RoomStatus.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/GetRoomUseCase.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/UpdateRoomUseCase.java
  kok-core/src/test/java/com/kok/kokcore/room/domain/RoomTest.java
Labels: ✨ Feature, 🥇 Urgency 1

#98 ✨ [Feature/vote] implement getting vote result API
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RoomParticipantQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/ResultResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VoteResultResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VotedMemberResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
  kok-api/src/test/java/com/kok/kokapi/room/adapter/out/persistence/RoomParticipantQueryRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/application/service/VoteServiceTest.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/vo/RoomStatus.java
  kok-core/src/main/java/com/kok/kokcore/room/port/out/LoadRoomParticipantPort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/LoadVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetVoteUseCase.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/SaveVoteUseCase.java
  kok-core/src/test/java/com/kok/kokcore/room/domain/RoomTest.java
Labels: ✨ Feature, 🥇 Urgency 1

#99 ✨ [Feature/vote] implement closing vote API
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/web/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomCommandService.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomCommandServiceTest.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/UpdateRoomUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1
