Repository depromeet/kok-server, pull requests merged in 2025-04, with the labels that each got.

#102 🚀 [Deploy/prod] refactor prod CD script & SSL config
  .github/workflows/kok-prod-CD.yml
  infra/docker-compose-blue.yml
  infra/docker-compose-env.yml
  infra/docker-compose-green.yml
  infra/docker-compose-nginx.yml
  infra/nginx/nginx.conf
  kok-api/src/main/resources/application-prod.yml
Labels: deploy, ✨ Feature

#103 🚀 [Deploy] change nginx reload to restart
  .github/workflows/kok-prod-CD.yml
Labels: bug, deploy

#101 ✨ [Feature/vote] implement getting vote final result API
  kok-api/src/main/java/com/kok/kokapi/station/adapter/in/web/StationController.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/CandidateResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/MemberVoteStatusResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VoteResultStationResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteKey.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateCommandRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/CandidateQueryRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/application/service/VoteServiceTest.java
  kok-api/src/test/resources/application-test.yml
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/vo/RoomStatus.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/vo/VoteStatus.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/DeleteVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/LoadVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/SaveVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetVoteUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1

#104 :bug: refactor: change swagger http to https
  kok-api/src/main/java/com/kok/kokapi/config/swagger/SwaggerConfig.java
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
Labels: deploy, fix

#106 🐛 [Fix/station] move changing route name logic into domain due to duplicated name save
  kok-api/src/main/resources/db/data/name.sql
  kok-core/src/main/java/com/kok/kokcore/station/domain/entity/Route.java
  kok-core/src/main/java/com/kok/kokcore/station/port/out/dto/StationRouteDto.java
Labels: fix

#107 ♻️ [Refactor/room] determine participant count by location input count on getting room detail API
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationRepository.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomDetailResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-api/src/test/java/com/kok/kokapi/room/adapter/in/web/RoomIntegrationTest.java
  kok-api/src/test/resources/application-test.yml
  kok-core/src/main/java/com/kok/kokcore/location/port/out/ReadLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/GetRoomUseCase.java
Labels: 🥇 Urgency 1, refactor

#109 ✨ [Feature/vote] fix key name error and add candidate count for getting vote deadline api
  kok-api/src/main/java/com/kok/kokapi/station/adapter/out/persistence/UserRecommendStationCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VoteDeadlineResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/CandidateService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetCandidateUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1, fix

#112 🐛 [Fix/candidate] remove candidate duplication
  kok-api/src/main/java/com/kok/kokapi/station/application/service/StationFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VoteDeadlineResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/CandidateService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetCandidateUseCase.java
Labels: bug

#113 :bug: [Fix/candidate] fix candidate-duplication
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
Labels: bug

#117 [Feature/vote] fix getting current result api due to change of UI
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/ResultResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VoteCurrentResultResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/dto/response/VotedMemberResponse.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteKey.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/CandidateService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
  kok-api/src/main/resources/db/migration/V4__change_priority_default.sql
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteCommandRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/adapter/out/persistence/VoteQueryRedisAdapterTest.java
  kok-api/src/test/java/com/kok/kokapi/vote/application/service/VoteServiceTest.java
  kok-api/src/test/java/com/kok/kokcore/vote/VoteResultsTest.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/GetRoomUseCase.java
  kok-core/src/main/java/com/kok/kokcore/vote/VoteResults.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/Vote.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/VoteResult.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/vo/ResultTag.java
  kok-core/src/main/java/com/kok/kokcore/vote/domain/vo/VoteStatus.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/DeleteVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/LoadVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/port/out/SaveVotePort.java
  kok-core/src/main/java/com/kok/kokcore/vote/usecase/GetVoteUseCase.java
Labels: ✨ Feature, 🥇 Urgency 1, refactor, fix

#118 [Feature/vote] remove closing vote api and close vote when all members voted
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomCommandService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-api/src/main/java/com/kok/kokapi/vote/adapter/in/web/VoteController.java
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteFacadeService.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomCommandServiceTest.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomQueryServiceTest.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/vo/RoomStatus.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/GetRoomUseCase.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/UpdateRoomUseCase.java
  kok-core/src/test/java/com/kok/kokcore/room/domain/RoomTest.java
Labels: ✨ Feature, 🥇 Urgency 1

#119 [Feature/vote] fix room status validation error when get current vote result
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
Labels: 🥇 Urgency 1, fix

#120 [Feature/vote] fix room status validation error when get current vote result
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
Labels: fix

#121 :bug: [Feature/vote] fix room status validation error due to wrong condition
  kok-api/src/main/java/com/kok/kokapi/vote/application/service/VoteService.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
Labels: 🥇 Urgency 1, fix
