Repository depromeet/kok-server, pull requests merged in 2025-02, with the labels that each got.

#24 :gear: [chore/develop] update .gitignore file
  .gitignore
Labels: chore

#25 ⚙️ [chore/develop] Implement CI/CD pipeline
  .github/workflows/README.md
  .github/workflows/kok-CI.yml
  .github/workflows/kok-dev-CD.yml
  .github/workflows/kok-prod-CD.yml
  .gitignore
  Dockerfile
  infra/docker-compose-blue.yml
  infra/docker-compose-dev.yml
  infra/docker-compose-green.yml
  infra/docker-compose-nginx.yml
  infra/nginx/nginx.conf
Labels: deploy

#27 ⚙️ [Chore/develop] automation test set up using jacoco
  build.gradle
Labels: chore

#26 ✨ [Feature/develop] set up application config
  build.gradle
  kok-api/build.gradle
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
  kok-api/src/main/resources/application.properties
Labels: ✨ Feature

#28 ✨ [feature/develop] implement common response code and error code
  kok-api/build.gradle
  kok-api/src/main/java/com/kok/kokapi/adapter/in/web/BaseController.java
  kok-api/src/main/java/com/kok/kokapi/adapter/in/web/HealthCheckController.java
  kok-api/src/main/java/com/kok/kokapi/application/service/HealthCheckService.java
  kok-api/src/main/java/com/kok/kokapi/application/usecase/HealthCheckUseCase.java
  kok-api/src/main/java/com/kok/kokapi/common/error/ErrorCode.java
  kok-api/src/main/java/com/kok/kokapi/common/exception/GlobalExceptionHandler.java
  kok-api/src/main/java/com/kok/kokapi/common/response/ApiResponseDto.java
Labels: ✨ Feature

#31 ⚙️ [chore/develop] setup redis config
  kok-api/src/main/java/com/kok/kokapi/config/redis/RedisConfig.java
  kok-api/src/main/resources/application-prod.yml
Labels: chore, 🥇 Urgency 1

#37 [feature/room-participant] implements room participation and get participant profiles
  kok-api/build.gradle
  kok-api/src/main/java/com/kok/kokapi/common/adapter/in/web/BaseController.java
  kok-api/src/main/java/com/kok/kokapi/config/jpa/JpaConfig.java
  kok-api/src/main/java/com/kok/kokapi/config/usecase/UseCaseConfig.java
  kok-api/src/main/java/com/kok/kokapi/monitoring/adapter/in/web/HealthCheckController.java
  kok-api/src/main/java/com/kok/kokapi/monitoring/application/service/HealthCheckService.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/request/CreateRoomRequest.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/request/JoinRoomParticipantRequest.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/MemberResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomDetailResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/dto/response/RoomMembersResponse.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/in/web/RoomController.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RedisSaveRoomPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RoomQueryRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/room/adapter/out/persistence/RoomSaveRedisAdapter.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomCreationService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomParticipantService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomQueryService.java
  kok-api/src/main/java/com/kok/kokapi/room/application/service/RoomService.java
  kok-api/src/test/java/com/kok/kokapi/common/config/ServiceTestConfig.java
  kok-api/src/test/java/com/kok/kokapi/room/application/service/RoomCreationServiceTest.java
  kok-core/build.gradle
  kok-core/src/main/java/com/kok/kokcore/application/port/out/SaveRoomPort.java
  kok-core/src/main/java/com/kok/kokcore/room/application/port/out/LoadRoomPort.java
  kok-core/src/main/java/com/kok/kokcore/room/application/port/out/SaveRoomPort.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Member.java
  kok-core/src/main/java/com/kok/kokcore/room/domain/Room.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/CreateRoomUseCase.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/GetRoomUseCase.java
  kok-core/src/main/java/com/kok/kokcore/room/usecase/JoinRoomUseCase.java
  kok-core/src/main/java/com/kok/kokcore/usecase/CreateRoomUseCase.java
  kok-core/src/test/java/com/kok/kokcore/room/domain/RoomTest.java
Labels: ✨ Feature, 🥇 Urgency 1

#34 ✨[Feature/centroid] user location and centroid
  .github/workflows/kok-dev-CD.yml
  .github/workflows/kok-prod-CD.yml
  .gitignore
  build.gradle
  infra/docker-compose-blue.yml
  infra/docker-compose-dev.yml
  infra/docker-compose-green.yml
  infra/docker-compose-nginx.yml
  kok-api/src/main/java/com/kok/kokapi/KokApiApplication.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/dto/LocationRequest.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/rest/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/dto/CentroidResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/dto/LocationResponse.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/mapper/LocationMapper.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationRepository.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/CentroidQueryService.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationCommandService.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationQueryService.java
  kok-api/src/main/java/com/kok/kokapi/config/geometry/GeometryConfig.java
  kok-api/src/main/java/com/kok/kokapi/config/geometry/PointConverter.java
  kok-api/src/main/resources/application-dev.yml
  kok-api/src/main/resources/application-prod.yml
  kok-core/src/main/java/com/kok/kokcore/application/domain/entity/Location.java
  kok-core/src/main/java/com/kok/kokcore/application/port/out/ReadCentroidPort.java
  kok-core/src/main/java/com/kok/kokcore/application/port/out/ReadLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/application/port/out/SaveLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/application/usecase/CreateLocationUsecase.java
  kok-core/src/main/java/com/kok/kokcore/application/usecase/ReadCentroidUsecase.java
  kok-core/src/main/java/com/kok/kokcore/application/usecase/ReadLocationUsecase.java
  kok-core/src/test/java/com/kok/kokcore/location/domain/LocationTest.java
Labels: ✨ Feature, 🥇 Urgency 1

#39 🐛fix: fix file architecture inconsistency
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/in/rest/LocationController.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/mapper/LocationMapper.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationPersistenceAdapter.java
  kok-api/src/main/java/com/kok/kokapi/centroid/adapter/out/persistence/LocationRepository.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/CentroidQueryService.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationCommandService.java
  kok-api/src/main/java/com/kok/kokapi/centroid/application/service/LocationQueryService.java
  kok-api/src/main/resources/application-dev.yml
  kok-core/src/main/java/com/kok/kokcore/location/application/port/out/ReadCentroidPort.java
  kok-core/src/main/java/com/kok/kokcore/location/application/port/out/ReadLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/location/application/port/out/SaveLocationPort.java
  kok-core/src/main/java/com/kok/kokcore/location/domain/Location.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/CreateLocationUsecase.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/ReadCentroidUsecase.java
  kok-core/src/main/java/com/kok/kokcore/location/usecase/ReadLocationUsecase.java
Labels: bug, 🥇 Urgency 1
